//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lifeflightapps : DbContext
    {
        public lifeflightapps()
            : base("name=lifeflightapps")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAmerigroupEmail> tblAmerigroupEmails { get; set; }
        public virtual DbSet<tblAuditLog> tblAuditLogs { get; set; }
        public virtual DbSet<tblBedStatusUpdate> tblBedStatusUpdates { get; set; }
        public virtual DbSet<tblCallerPreferredNumber> tblCallerPreferredNumbers { get; set; }
        public virtual DbSet<tblCaller> tblCallers { get; set; }
        public virtual DbSet<tblCallerTitle> tblCallerTitles { get; set; }
        public virtual DbSet<tblCareLevel> tblCareLevels { get; set; }
        public virtual DbSet<tblCareLevelChange> tblCareLevelChanges { get; set; }
        public virtual DbSet<tblChargeRNPageOnOff> tblChargeRNPageOnOffs { get; set; }
        public virtual DbSet<tblConfirmationEmailEM> tblConfirmationEmailEMS { get; set; }
        public virtual DbSet<tblConfirmationPage> tblConfirmationPages { get; set; }
        public virtual DbSet<tblDelayReason> tblDelayReasons { get; set; }
        public virtual DbSet<tblDeleteRecord> tblDeleteRecords { get; set; }
        public virtual DbSet<tblDischargeATNumber> tblDischargeATNumbers { get; set; }
        public virtual DbSet<tblDischargeComplaint> tblDischargeComplaints { get; set; }
        public virtual DbSet<tblDischargeComplaintLog> tblDischargeComplaintLogs { get; set; }
        public virtual DbSet<tblDischargeComplaintType> tblDischargeComplaintTypes { get; set; }
        public virtual DbSet<tblDischargeNeed> tblDischargeNeeds { get; set; }
        public virtual DbSet<tblDischargeRequest> tblDischargeRequests { get; set; }
        public virtual DbSet<tblDischargeRequestLog> tblDischargeRequestLogs { get; set; }
        public virtual DbSet<tblDischargeRequestPageLog> tblDischargeRequestPageLogs { get; set; }
        public virtual DbSet<tblDischargeRequestPhoneNumber> tblDischargeRequestPhoneNumbers { get; set; }
        public virtual DbSet<tblDischargeRequestUnit> tblDischargeRequestUnits { get; set; }
        public virtual DbSet<tblDrivingInfo> tblDrivingInfoes { get; set; }
        public virtual DbSet<tblEmailAddress> tblEmailAddresses { get; set; }
        public virtual DbSet<tblEmailQueue> tblEmailQueues { get; set; }
        public virtual DbSet<tblEmsAgencyLocal> tblEmsAgencyLocals { get; set; }
        public virtual DbSet<tblEMSAgencyRate> tblEMSAgencyRates { get; set; }
        public virtual DbSet<tblEMSArrivedBedsideLog> tblEMSArrivedBedsideLogs { get; set; }
        public virtual DbSet<tblInsuranceAgency> tblInsuranceAgencies { get; set; }
        public virtual DbSet<tblInsuranceAgencyContact> tblInsuranceAgencyContacts { get; set; }
        public virtual DbSet<tblInsuranceCompany> tblInsuranceCompanies { get; set; }
        public virtual DbSet<tblInsuranceCompanyContact> tblInsuranceCompanyContacts { get; set; }
        public virtual DbSet<tblInsuranceEmsXref> tblInsuranceEmsXrefs { get; set; }
        public virtual DbSet<tblLogonEvent> tblLogonEvents { get; set; }
        public virtual DbSet<tblMbrCensu> tblMbrCensus { get; set; }
        public virtual DbSet<tblMbrCoverage> tblMbrCoverages { get; set; }
        public virtual DbSet<tblMbrInsurance> tblMbrInsurances { get; set; }
        public virtual DbSet<tblMedicareCode> tblMedicareCodes { get; set; }
        public virtual DbSet<tblNursingHome> tblNursingHomes { get; set; }
        public virtual DbSet<tblPageLog> tblPageLogs { get; set; }
        public virtual DbSet<tblPatient> tblPatients { get; set; }
        public virtual DbSet<tblPatientNote> tblPatientNotes { get; set; }
        public virtual DbSet<tblPrintFaxLog> tblPrintFaxLogs { get; set; }
        public virtual DbSet<tblQuote> tblQuotes { get; set; }
        public virtual DbSet<tblQuotesTransfer> tblQuotesTransfers { get; set; }
        public virtual DbSet<tblRateConversion> tblRateConversions { get; set; }
        public virtual DbSet<tblRecordOpened> tblRecordOpeneds { get; set; }
        public virtual DbSet<tblRecordOpenedTransfer> tblRecordOpenedTransfers { get; set; }
        public virtual DbSet<tblRequestStatu> tblRequestStatus { get; set; }
        public virtual DbSet<tblSpecialNeed> tblSpecialNeeds { get; set; }
        public virtual DbSet<tblTransferRequest> tblTransferRequests { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblVUMCPayorReason> tblVUMCPayorReasons { get; set; }
        public virtual DbSet<tblBuilding> tblBuildings { get; set; }
        public virtual DbSet<tblHospital> tblHospitals { get; set; }
        public virtual DbSet<tblICDCode> tblICDCodes { get; set; }
        public virtual DbSet<tblTransportMode> tblTransportModes { get; set; }
        public virtual DbSet<tblZipCityState> tblZipCityStates { get; set; }
        public virtual DbSet<Union_Facilities> Union_Facilities { get; set; }
        public virtual DbSet<tblDischargeRequest1> tblDischargeRequests1 { get; set; }
        public virtual DbSet<tblDischargeDestination> tblDischargeDestinations { get; set; }
        public virtual DbSet<tblDischargePickup> tblDischargePickups { get; set; }
    }
}
