//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAmerigroupEmail
    {
        public int AmerigroupEmailedID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<System.DateTime> EmailedDateTime { get; set; }
        public string emailedBy { get; set; }
    }
}
