//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLog
    {
        public int ID { get; set; }
        public string APPNAME { get; set; }
        public int IDFROMAPP { get; set; }
        public string MRNUMBER { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string UPDATENOTES { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
    }
}
