//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBedStatusUpdate
    {
        public int BedStatusUpdatedID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public Nullable<System.DateTime> UpdatedWhen { get; set; }
        public string Staff { get; set; }
    }
}
