//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCaller()
        {
            this.tblCallerPreferredNumbers = new HashSet<tblCallerPreferredNumber>();
        }
    
        public int ID { get; set; }
        public string CallerLastName { get; set; }
        public string CallerFirstName { get; set; }
        public string CallerTitle { get; set; }
        public Nullable<double> OfficePhone { get; set; }
        public string CallerPager { get; set; }
        public Nullable<double> MobilePhone { get; set; }
        public string CallerEmail { get; set; }
        public string Assignment { get; set; }
        public Nullable<bool> Active { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCallerPreferredNumber> tblCallerPreferredNumbers { get; set; }
    }
}
