//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfirmationPage
    {
        public int confirmationpageID { get; set; }
        public Nullable<int> requestID { get; set; }
        public Nullable<System.DateTime> senton { get; set; }
        public string senttoname { get; set; }
        public string senttopager { get; set; }
        public string sentby { get; set; }
        public string message { get; set; }
    }
}
