//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallerPreferredNumber
    {
        public int CallerPreferredID { get; set; }
        public int CallerId { get; set; }
        public string PreferredNumber { get; set; }
        public string PreferredType { get; set; }
    
        public virtual tblCaller tblCaller { get; set; }
    }
}
