//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCareLevelChange
    {
        public int CareLevelChangeID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public Nullable<int> RequestedCareLevel { get; set; }
        public Nullable<int> NeededCareLevel { get; set; }
        public string Comments { get; set; }
        public string vunetID { get; set; }
        public Nullable<System.DateTime> datetimeentered { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
