//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeRequest
    {
        public int ReqID { get; set; }
        public Nullable<System.DateTime> ReqDateTime { get; set; }
        public string ReqTakerVuNet { get; set; }
        public string reqStatus { get; set; }
        public Nullable<int> CallerID { get; set; }
        public string CallerName { get; set; }
        public string CallerPhone { get; set; }
        public string CallerPager { get; set; }
        public string CallerTitle { get; set; }
        public string CallerFax { get; set; }
        public Nullable<System.DateTime> PickUpDateTime { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public Nullable<int> PickupBldg { get; set; }
        public string PickUpUnit { get; set; }
        public string PickUpRoom { get; set; }
        public Nullable<int> DestinationFacilityFVID { get; set; }
        public string DestinationFacility { get; set; }
        public string DestinationAddress { get; set; }
        public string DestinationCity { get; set; }
        public string DestinationState { get; set; }
        public string DestinationZip { get; set; }
        public string DestinationCounty { get; set; }
        public string DestinationRoom { get; set; }
        public string DestinationPhone { get; set; }
        public Nullable<int> GroundMiles { get; set; }
        public string GroundTime { get; set; }
        public string TransportMode { get; set; }
        public string EMSRotationAgency { get; set; }
        public Nullable<System.DateTime> EMSAgencyAssignedDateTime { get; set; }
        public Nullable<int> EMSAgencyID { get; set; }
        public string EMSAgency { get; set; }
        public string EMSAgencyPhone { get; set; }
        public Nullable<System.DateTime> EMSAgencyReqDateTime { get; set; }
        public string EMSAgencyCareLevel { get; set; }
        public Nullable<System.DateTime> EMSAgencyBedSide { get; set; }
        public Nullable<bool> EMSAgencyBedsidePageSent { get; set; }
        public string EMSAgencySpecialInstructions { get; set; }
        public Nullable<int> TransportCost { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientMRN { get; set; }
        public Nullable<System.DateTime> PatientDOB { get; set; }
        public string PatientSS { get; set; }
        public string PatientAddress { get; set; }
        public string PatientCity { get; set; }
        public string PatientState { get; set; }
        public string PatientZipcode { get; set; }
        public string PatientCounty { get; set; }
        public string PatientPhone { get; set; }
        public Nullable<int> PatientWeight { get; set; }
        public Nullable<bool> PatientInfectios { get; set; }
        public string PatientAgeAtTransport { get; set; }
        public string ICD9 { get; set; }
        public string ICD9Diagnosis { get; set; }
        public string InsuranceProvider { get; set; }
        public string InsuranceIDNumber { get; set; }
        public Nullable<bool> RequiresPreauth { get; set; }
        public string InsurancePhone { get; set; }
        public string PrimaryPayor { get; set; }
        public string PayorVUMCReason { get; set; }
        public string ATNumber { get; set; }
        public string AuthNumber { get; set; }
        public Nullable<System.DateTime> AuthorizationRx { get; set; }
        public Nullable<bool> PreAuthComplete { get; set; }
        public Nullable<bool> Oxygen { get; set; }
        public Nullable<bool> IVMeds { get; set; }
        public Nullable<bool> CardiacMonitor { get; set; }
        public Nullable<bool> PulseOx { get; set; }
        public Nullable<bool> Pacer { get; set; }
        public Nullable<bool> Isolette { get; set; }
        public Nullable<bool> CPAP { get; set; }
        public Nullable<bool> BiPap { get; set; }
        public Nullable<bool> VAD { get; set; }
        public Nullable<bool> Trach { get; set; }
        public Nullable<bool> Ventilator { get; set; }
        public Nullable<bool> BalloonPump { get; set; }
        public Nullable<bool> ComplaintExists { get; set; }
        public string ConfirmationPagetoCallerSent { get; set; }
        public string MedicalNecessityFormEmailed { get; set; }
        public string EmailSentToFirstCall { get; set; }
        public Nullable<System.DateTime> BedStatusUpdated { get; set; }
        public Nullable<int> VUEMSUnit { get; set; }
        public Nullable<int> FatigueScore { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
