//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeRequestUnit
    {
        public string ReqBuilding { get; set; }
        public string ReqUnit { get; set; }
        public int reqUnitID { get; set; }
        public Nullable<int> UnitPhone { get; set; }
        public string CNPager { get; set; }
    }
}
