//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeNeed
    {
        public int dischargeneedid { get; set; }
        public int patientid { get; set; }
        public int specialneedsid { get; set; }
        public bool active { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
        public virtual tblSpecialNeed tblSpecialNeed { get; set; }
    }
}
