//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeComplaint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDischargeComplaint()
        {
            this.tblDischargeComplaintLogs = new HashSet<tblDischargeComplaintLog>();
        }
    
        public int DischargeComplaintID { get; set; }
        public int RequestID { get; set; }
        public System.DateTime ComplaintEntereddatetime { get; set; }
        public string EnteredBy { get; set; }
        public bool HospitalAOCNotified { get; set; }
        public string Complaint { get; set; }
        public Nullable<System.DateTime> ResolvedDateTime { get; set; }
        public bool Resolved { get; set; }
        public Nullable<int> ComplaintTypeID { get; set; }
        public Nullable<int> DelayReasonID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual tblDelayReason tblDelayReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDischargeComplaintLog> tblDischargeComplaintLogs { get; set; }
        public virtual tblDischargeComplaintType tblDischargeComplaintType { get; set; }
    }
}
