//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDischargeRequestPageLog
    {
        public int pageID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string DCStaff { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string senttoPager { get; set; }
        public string senttoName { get; set; }
        public string message { get; set; }
    }
}
