//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEMSArrivedBedsideLog
    {
        public int emsconfpageID { get; set; }
        public Nullable<int> reqID { get; set; }
        public string sentby { get; set; }
        public Nullable<System.DateTime> sentondatetime { get; set; }
        public string senttoname { get; set; }
        public string senttopager { get; set; }
    }
}
