//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmsAgencyLocal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmsAgencyLocal()
        {
            this.tblInsuranceEmsXrefs = new HashSet<tblInsuranceEmsXref>();
            this.tblDischargeRequests = new HashSet<tblDischargeRequest1>();
        }
    
        public int EMSID { get; set; }
        public Nullable<int> RotationSequence { get; set; }
        public Nullable<int> RotationSequenceTranser { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string Notes { get; set; }
        public string Phones { get; set; }
        public string Nextel { get; set; }
        public string SpecialEquipment { get; set; }
        public bool LocalUse { get; set; }
        public Nullable<bool> TransferUse { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> MileageRate { get; set; }
        public string DispatchEmail { get; set; }
        public string taxID { get; set; }
        public Nullable<bool> BLS { get; set; }
        public string ALS { get; set; }
        public string Vent { get; set; }
        public string Bariatric { get; set; }
        public string IVPump { get; set; }
        public string Other { get; set; }
        public string Type { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsuranceEmsXref> tblInsuranceEmsXrefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDischargeRequest1> tblDischargeRequests { get; set; }
    }
}
