//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEMSAgencyRate
    {
        public int RateID { get; set; }
        public Nullable<int> EMSAgencyID { get; set; }
        public Nullable<decimal> A0425 { get; set; }
        public Nullable<decimal> A0426 { get; set; }
        public Nullable<decimal> A0427 { get; set; }
        public Nullable<decimal> A0428 { get; set; }
        public Nullable<decimal> A0429 { get; set; }
        public Nullable<decimal> A0430 { get; set; }
        public Nullable<decimal> A0434 { get; set; }
        public Nullable<decimal> A0435 { get; set; }
    }
}
