//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string Notes { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Airport { get; set; }
        public string County { get; set; }
        public string Type { get; set; }
        public int ID2 { get; set; }
        public string Address2 { get; set; }
        public string GPSWaypoint { get; set; }
        public string VideoURL { get; set; }
        public int HudID { get; set; }
        public bool Deleted { get; set; }
        public bool EMRC { get; set; }
        public string Country { get; set; }
        public Nullable<int> PUDOFixedType { get; set; }
        public Nullable<int> PUDOFixedID { get; set; }
        public string PUDOFixedDescription { get; set; }
        public Nullable<double> PUDOFixedLat { get; set; }
        public Nullable<double> PUDOFixedLon { get; set; }
        public Nullable<int> PUDORotorType { get; set; }
        public Nullable<int> PUDORotorID { get; set; }
        public string PUDORotorDescription { get; set; }
        public Nullable<double> PUDORotorLat { get; set; }
        public Nullable<double> PUDORotorLon { get; set; }
        public Nullable<int> PUDOGroundType { get; set; }
        public Nullable<int> PUDOGroundID { get; set; }
        public string PUDOGroundDescription { get; set; }
        public Nullable<double> PUDOGroundLat { get; set; }
        public Nullable<double> PUDOGroundLon { get; set; }
        public Nullable<int> DefaultPUDOType { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> JurisdictionID { get; set; }
        public string Phone { get; set; }
        public bool SharedWithFlightcall { get; set; }
        public string Image { get; set; }
        public string WebSite { get; set; }
    }
}
