//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsuranceCompany
    {
        public int InsuranceCompanyID { get; set; }
        public string InsuranceName { get; set; }
        public string InsurancePhone { get; set; }
        public string InsuranceFax { get; set; }
        public Nullable<bool> PreauthRequired { get; set; }
        public string LinktoDocumentation { get; set; }
        public string Instructions { get; set; }
        public Nullable<bool> HasOwnPaperowork { get; set; }
        public string ReportName { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
