//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsuranceAgency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInsuranceAgency()
        {
            this.tblInsuranceAgencyContacts = new HashSet<tblInsuranceAgencyContact>();
            this.tblInsuranceEmsXrefs = new HashSet<tblInsuranceEmsXref>();
        }
    
        public int INSURANCEID { get; set; }
        public string INSAGENCYNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string INSURANCEPHONE { get; set; }
        public string INSURANCEFAX { get; set; }
        public string INSTRUCTIONS { get; set; }
        public Nullable<bool> PREAUTHREQUIRED { get; set; }
        public Nullable<bool> HASOWNPAPEROWORK { get; set; }
        public string CREATEDBY { get; set; }
        public System.DateTime CREATEDON { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsuranceAgencyContact> tblInsuranceAgencyContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInsuranceEmsXref> tblInsuranceEmsXrefs { get; set; }
    }
}
