//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInsuranceEmsXref
    {
        public int InsuranceEmsID { get; set; }
        public int InsuranceProviderID { get; set; }
        public int AgencyId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual tblEmsAgencyLocal tblEmsAgencyLocal { get; set; }
        public virtual tblInsuranceAgency tblInsuranceAgency { get; set; }
    }
}
