//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogonEvent
    {
        public int logoneventID { get; set; }
        public string vunetID { get; set; }
        public Nullable<System.DateTime> logondatetime { get; set; }
    }
}
