//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedicareCode
    {
        public string HCPCSCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MedicareAllowable { get; set; }
        public Nullable<decimal> VUMCRate { get; set; }
    }
}
