//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMbrCoverage
    {
        public int MbrCoverageID { get; set; }
        public string MrNumber { get; set; }
        public int CoverageTypeID { get; set; }
        public string CoverageTypeName { get; set; }
        public bool IsActive { get; set; }
        public string VerifiedStatus { get; set; }
        public string VerifiedByUser { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
