//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMbrInsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMbrInsurance()
        {
            this.tblDischargeRequests = new HashSet<tblDischargeRequest1>();
        }
    
        public int MbrInsuranceID { get; set; }
        public long InsuranceID { get; set; }
        public string MedipacPlanID { get; set; }
        public int PayorID { get; set; }
        public int PlanID { get; set; }
        public int FillingOrder { get; set; }
        public string MrNumber { get; set; }
        public string PayorName { get; set; }
        public string PlanName { get; set; }
        public string PlanType { get; set; }
        public string SubscriberName { get; set; }
        public string FinancialName { get; set; }
        public Nullable<System.DateTime> Effective { get; set; }
        public Nullable<System.DateTime> Termination { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AuthCode { get; set; }
        public string ICDCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDischargeRequest1> tblDischargeRequests { get; set; }
    }
}
