//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNursingHome
    {
        public int NursingHomeID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public Nullable<double> Zip { get; set; }
        public Nullable<int> Miles { get; set; }
        public Nullable<int> DriveTime { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> UseInScholarships { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
