//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageLog
    {
        public int PageLogId { get; set; }
        public int DischargeRequestId { get; set; }
        public string Receipents { get; set; }
        public string MessageType { get; set; }
        public string Message { get; set; }
        public System.DateTime SentOn { get; set; }
        public string Response { get; set; }
    
        public virtual tblDischargeRequest1 tblDischargeRequest { get; set; }
    }
}
