//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DischargeTransportManagement.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientNote
    {
        public int patientID { get; set; }
        public Nullable<int> ptMRN { get; set; }
        public string ptNotes { get; set; }
        public string enteredBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
